version: '3.9'

services:
    rust-server:
        container_name: rust-server
        image: ryanpaulgannon/rust-server:1.0.0
        build:
            context: .
            dockerfile: dockerfile
            args:
                DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
        ports:
            - '8080:8080'
        depends_on:
            - rust-api-db
    rust-api-db:
        container_name: rust-api
        image: postgres:15
        restart: always
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=${DOCKER_USER}
            - POSTGRES_PASSWORD=${DOCKER_PASSWORD}
            - POSTGRES_DB=${DOCKER_DB}
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
